name: Update Shadowrocket Config

on:
  # 手动执行
  workflow_dispatch:

  # 每天 UTC 03:00 自动执行
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download Latest Shadowrocket Config
        run: |
          mkdir -p output

          curl -L \
            https://raw.githubusercontent.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/release/sr_top500_banlist_ad.conf \
            -o output/shadowrocket.conf

      - name: Patch Config
        env:
          NEXTDNS_PROFILE: ${{ secrets.NEXTDNS_PROFILE }}
        run: |
          python scripts/update.py

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add output/shadowrocket.conf

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "Auto update Shadowrocket config"

          git push